import { prisma } from '@/lib/prisma';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

// Run with: npx prisma db seed
// Prisma 7: register the seed command in prisma.config.ts:
//   migrations: { path: "prisma/migrations", seed: "tsx prisma/seed.ts" }

type CategoryJson = {
  id: number;
  name: string;
  slug: string;
};

type ProductJson = {
  id: number;
  title: string;
  description: string;
  price: number;
  stock: number;
  brand?: string;
  sku: string;
  categoryId: number;
};

type ProductsJson = {
  products: ProductJson[];
  categories: CategoryJson[];
};

/**
 * Convert a product title to a URL-friendly slug.
 *
 * Example:
 * "Eyeshadow Palette with Mirror"
 * -> "eyeshadow-palette-with-mirror"
 */
function slugify(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Slugs must be unique in the database. Some titles in the JSON
 * produce the same slug (e.g. "Rolex Cellini Moonphase" appears twice),
 * so when a slug is already taken we append the product id.
 * The order of products.json is stable, so the result is deterministic
 * and the seed can safely be re-run.
 */
function createUniqueSlug(title: string, id: number, usedSlugs: Set<string>): string {
  const base = slugify(title) || `product-${id}`;

  let slug = base;
  if (usedSlugs.has(slug)) {
    slug = `${base}-${id}`;
  }

  usedSlugs.add(slug);
  return slug;
}

async function main() {
  const jsonPath = path.join(process.cwd(), './data/products.json');

  const file = await readFile(jsonPath, 'utf8');
  const data: ProductsJson = JSON.parse(file);

  console.log(`Found ${data.categories.length} categories and ${data.products.length} products.`);

  /**
   * 1) Categories first, because products reference them via categoryId.
   *    Category.id has no default in the schema, so we use the ids
   *    from the JSON. Upsert keeps the seed re-runnable.
   */
  for (const category of data.categories) {
    await prisma.category.upsert({
      where: { id: category.id },
      update: {
        name: category.name,
        slug: category.slug,
      },
      create: {
        id: category.id,
        name: category.name,
        slug: category.slug,
      },
    });
  }

  console.log(`Seeded ${data.categories.length} categories.`);

  /**
   * 2) Products.
   *    Upsert by sku (unique) instead of deleteMany(), so re-running the
   *    seed neither duplicates rows nor fails on existing OrderItem
   *    foreign keys. Product.id (uuid) is generated by the database.
   */
  const usedSlugs = new Set<string>();

  for (const product of data.products) {
    const fields = {
      slug: createUniqueSlug(product.title, product.id, usedSlugs),
      title: product.title,
      description: product.description,
      price: product.price.toFixed(2),
      stock: product.stock,
      brand: product.brand ?? null,
      categoryId: product.categoryId,
    };

    await prisma.product.upsert({
      where: { sku: product.sku },
      update: fields,
      create: { ...fields, sku: product.sku },
    });
  }

  console.log(`Seeded ${data.products.length} products.`);
}

main()
  .catch((error) => {
    console.error('Seed failed:');
    console.error(error);

    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
